package webTest.edge;
// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.apache.commons.io.FileUtils;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.edge.EdgeOptions;

import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

public class ComprarCursoEveclass {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public void setUp() {
        WebDriverManager.edgedriver().setup();
        EdgeOptions options = new EdgeOptions();
        // Configurações adicionais, se necessário
        driver = new EdgeDriver(options);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS); // Espera até que o elemento seja encotrado
    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void testeCompraCurso() throws InterruptedException, IOException {
        // Iniciando Teste acessando o site Testando Eveclass
        driver.get("https://testando.eveclass.com/pt");

        driver.manage().window().setSize(new Dimension(1580, 840));

        // Aciona o botão "Começar Agora"
        driver.findElement(By.cssSelector(".button-custom:nth-child(4) > .button-text > span > span")).click();

        // Aciona o botão "Entrar"
        driver.findElement(By.cssSelector("#support-action > span > span > span")).click();

        // Seleciona o Input "Email" e inseri os valores
        WebElement inputEmail = driver.findElement(By.cssSelector("input[data-vv-as='Email'][type='Email']"));
        inputEmail.sendKeys("testerj11@yopmail.com");

        // Seleciona o Input "password" e inseri os valores
        WebElement inputSenha = driver.findElement(By.cssSelector("input[type='password']"));
        inputSenha.sendKeys("123456");

        // Aciona o botão "Entrar"
        driver.findElement(By.xpath("//*[@id=\"auth-panel\"]/div[2]/div/div/div/div/div[2]/div/form/div[2]/button/span/span")).click();

        // Aciona o botão "Procurar Curso"
        driver.findElement(By.cssSelector("#my-courses > div > div > div > a > span > span")).click();

        // Seleciona o curso desejado
        driver.findElement(By.cssSelector("div[data-src='https://cdn.eveclass.com/p/62bf145fd8ff1ef247cd4eda/files/gallery/image/94c9d7f0-1354-11ed-9b44-a528fdf69ab8/thumbnail.png']")).click();

        // Aciona o botão "Comprar"
        driver.findElement(By.linkText("Comprar")).click();

        // Seleciona o Input "CPF" e inseri os valores
        WebElement inputCpf = driver.findElement(By.cssSelector("input[data-vv-as='CPF'][type='text']"));
        inputCpf.clear(); // Limpa o input
        inputCpf.sendKeys("56483801785"); // Inseri os valores no input

        // Seleciona o Input "telefone" e inseri os valores
        WebElement inputTelefone = driver.findElement(By.cssSelector("input[data-vv-as='Telefone'][type='text']"));
        inputTelefone.clear(); // Limpa o input
        inputTelefone.sendKeys("2193801785");

        // Seleciona o Input "CEP" e inseri os valores
        WebElement inputCep = driver.findElement(By.cssSelector("input[data-vv-as='CEP'][type='text']"));
        inputCep.clear(); // Limpa o input
        inputCep.sendKeys("21240250");

        // Seleciona o Input "Número" e inseri os valores
        WebElement inputNmr = driver.findElement(By.cssSelector("input[data-vv-as='Número'][type='text']"));
        inputNmr.sendKeys("71");
        Thread.sleep(2000); // espera por 2 segundos

        // Aciona o botão "Confirmar Compra"
        driver.findElement(By.cssSelector("#app > div > div.checkout-action > div > div.checkout-form > form > button > span > span > span")).click();

        Thread.sleep(2000); // espera por 2 segundos
        assertThat(driver.findElement(By.xpath("//h1[text()='Compra realizada com sucesso!']")).isDisplayed(), is(true));

        // Verifica se o texto esperado é igual ao texto atual
        assertThat(driver.findElement(By.cssSelector("div.title h1")).getText(), is("Compra realizada com sucesso!"));

        // Gera um print-screen do final do Teste para verificação
        File screenshot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
        FileUtils.copyFile(screenshot, new File("src/test/resources/utils/print/evidenciaComprarCursoEdge.png"));
    }
}
