package webTest.edge;
// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.apache.commons.io.FileUtils;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.edge.EdgeOptions;

import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

public class ContatoEveclass {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        WebDriverManager.edgedriver().setup();
        EdgeOptions options = new EdgeOptions();
        // Configurações adicionais, se necessário
        driver = new EdgeDriver(options);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS); // Espera até que o elemento seja encotrado
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void EntrarEmContato() throws IOException, InterruptedException {
        driver.get("https://testando.eveclass.com/pt");
        driver.manage().window().setSize(new Dimension(1382, 736));
        // Aciona o botão "Começar Agora"
        driver.findElement(By.cssSelector(".button-custom:nth-child(4) > .button-text > span > span")).click();
        driver.findElement(By.cssSelector(".fal.fa-comment-smile")).click();
        // Seleciona o Input "Nome"
        WebElement inputNome = driver.findElement(By.cssSelector("input[data-vv-as='Nome'][type='text']"));
        inputNome.sendKeys("Maria Angélica");
        // Seleciona o Input "Email" e inseri os valores
        WebElement inputEmail = driver.findElement(By.cssSelector("input[data-vv-as='Email'][type='Email']"));
        inputEmail.sendKeys("mangelicakffuri@gmail.com");
        // Localiza o elemento textarea pelo atributo placeholder
        WebElement textareaMensagem = driver.findElement(By.cssSelector("textarea[placeholder='Digite aqui a sua mensagem']"));
        // Insere o texto "Digite aqui a sua mensagem" no campo de entrada de texto
        textareaMensagem.sendKeys("Testando Mensagem Contato");
        // Localiza o elemento button pelo atributo class
        WebElement buttonEnviar = driver.findElement(By.cssSelector("button.button-custom"));
        // Realiza o clique no botão "Enviar"
        buttonEnviar.click();
        Thread.sleep(2000); // espera por 2 segundos
        // Gera um print-screen do final do Teste para verificação
        File screenshot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
        FileUtils.copyFile(screenshot, new File("src/test/resources/utils/print/evidenciaContatoEdge.png"));
        // Localiza o elemento button pelo atributo class
        WebElement buttonFechar = driver.findElement(By.cssSelector("button.swal2-confirm"));
        // Realiza o clique no botão "Fechar"
        buttonFechar.click();

    }
}