package webTest.firefox;
// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.apache.commons.io.FileUtils;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;


import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

public class CriarContaEveclass {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public void setUp() {
        WebDriverManager.firefoxdriver().setup();

        FirefoxOptions options = new FirefoxOptions();
        // Configurar opções do Firefox, se necessário
        // options.addArguments("...");

        driver = new FirefoxDriver(options);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS); // Espera até que o elemento seja encotrado
    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void testeCriarConta() throws IOException {
        // Iniciando Teste acessando o site Testando Eveclass
        driver.get("https://testando.eveclass.com/pt");

        // Altera dimensão da tela para visualização
        driver.manage().window().setSize(new Dimension(1580, 840));

        // Aciona o botão "Começar Agora"
        driver.findElement(By.cssSelector(".button-custom:nth-child(4) > .button-text > span > span")).click();

        // Aciona o botão "Criar Conta"
        driver.findElement(By.cssSelector("#main-action > .button-text > span > span")).click();

        // Seleciona o Input "Seu nome completo" e inseri os valores
        WebElement inputNomeCompleto = driver.findElement(By.cssSelector("input[data-vv-as='Seu nome completo'][type='text']"));
        inputNomeCompleto.sendKeys("Cristiano");

        // Seleciona o Input "Seu email" e inseri os valores
        WebElement inputEmail = driver.findElement(By.cssSelector("input[data-vv-as='Seu email'][type='text']"));
        inputEmail.sendKeys("testerj11@yopmail.com");

        // Seleciona o Input "Confirme seu email" e inseri os valores
        WebElement inputConfirmeEmail = driver.findElement(By.cssSelector("input[data-vv-as='Confirme seu email'][type='text']"));
        inputConfirmeEmail.sendKeys("testerj11@yopmail.com");

        // Aciona o botão "Próximo"
        driver.findElement(By.cssSelector(".button-text > span")).click();

        // Seleciona o Input "password" e inseri os valores
        WebElement inputSenha = driver.findElement(By.cssSelector("input[type='password']"));
        inputSenha.sendKeys("123456");

        // Verifica se a lista inputsSenha tem mais de um elemento antes de tentar acessar o segundo elemento.
        // Se houver mais de um elemento, o segundo elemento será selecionado e o texto "123456789" será inserido no campo de senha.
        // Se houver apenas um elemento, uma mensagem de aviso será impressa no console.
        List<WebElement> inputsSenha = driver.findElements(By.cssSelector("input[type='password']"));
        if (inputsSenha.size() > 1) {
            WebElement segundoInputSenha = inputsSenha.get(1);
            segundoInputSenha.sendKeys("123456");
        } else {
            System.out.println("Apenas um campo de senha encontrado.");
        }

        // Aciona o botão "Criar Conta"
        driver.findElement(By.cssSelector(".button-text > span")).click();

        // Verifica se o texto esperado é igual ao texto atual
        assertThat(driver.findElement(By.id("swal2-title")).getText(), is("Cadastro concluído com sucesso!"));

        // Gera um print-screen do final do Teste para verificação
        File screenshot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
        FileUtils.copyFile(screenshot, new File("src/test/resources/utils/print/evidenciaCriarContaFirefox.png"));
    }
}
